- name: Allow app to use unix domain socket
  become: yes
  file:
    path: /var/run/
    mode: '0777'
    state: directory

- name: Restart nginx
  become: yes
  systemd:
    name: nginx.service
    state: restarted
