- name: Remove webapp dir
  file:
    path: /home/isucon/webapp
    state: absent

- name: Clone this repo
  git:
    repo: https://github.com/hiroyaonoe/isucon12-qualify.git
    dest: /home/isucon/webapp
    version: "{{ git_branch_name }}"
