- name: Build go app
  command:
    cmd: /home/isucon/local/go/bin/go build
    chdir: /home/isucon/webapp/go

- name: Restart go app
  become: yes
  systemd:
    name: isucondition.go.service
    state: restarted
