- name: "common roles"
  hosts: all
  roles:
    - common

# - name: "bench roles"
#   hosts: bench
#   roles:
#     - bench

# - name: "webapp roles"
#   hosts: webapp
#   roles:
#     - webapp

- name: "webapp1 roles"
  hosts: webapp1
  roles:
    - webapp/alp
    - webapp/go
    - webapp/nginx

- name: "webapp2 roles"
  hosts: webapp2
  roles:
    - webapp/pt-query-digest
    - webapp/mysql
    - webapp/redis

- name: "webapp3 roles"
  hosts: webapp3
  roles:
    - webapp/alp
    - webapp/go
    - webapp/nginx
