name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  go-fmt:
    name: go fmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21.x'
      - name: Format Go
        run: | 
          result=$(gofmt -l . | wc -l)
          if [ $result -ne 0 ]; then
            exit 1
          fi

  terraform-fmt:
    name: terraform fmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.5
      - name: Format terraform
        working-directory: ./terraform
        run: terraform fmt -recursive -check
      - name: Validate terraform
        working-directory: ./terraform
        run: |
          terraform init
          terraform validate
